### ISSUE TITLE
配置条件属性的条件左值为属性有问题

### ISSUE THREAD

**Issue by howell86** [youseries/ureport#123]
版本号:2.2.1
配置条件属性的条件左值为“属性”，查看报表报错：
报表计算出错，错误信息如下：
java.lang.IllegalArgumentException: No bean specified 
at org.apache.commons.beanutils.PropertyUtilsBean.getNestedProperty(PropertyUtilsBean.java:734) 
at org.apache.commons.beanutils.PropertyUtilsBean.getProperty(PropertyUtilsBean.java:846) 
at org.apache.commons.beanutils.PropertyUtils.getProperty(PropertyUtils.java:426) 
at com.bstek.ureport.Utils.getProperty(Utils.java:154) 
at com.bstek.ureport.expression.model.condition.PropertyExpressionCondition.computeLeft(PropertyExpressionCondition.java:40) 
at com.bstek.ureport.expression.model.condition.BaseCondition.filter(BaseCondition.java:48) 
at com.bstek.ureport.model.Cell.doComputeConditionProperty(Cell.java:305) 
at com.bstek.ureport.model.Cell.doCompute(Cell.java:257) 
at com.bstek.ureport.build.ReportBuilder.recomputeCells(ReportBuilder.java:302) 
at com.bstek.ureport.build.ReportBuilder.buildReport(ReportBuilder.java:86)

**Comment by youseries** [comment]
是你单元格绑定对象有问题。
