### ISSUE TITLE
SQL中条件表达式解析错误，emptyparam(无默认值的参数)!=true

### ISSUE THREAD

**Issue by muxiaoshan** [youseries/ureport#137]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

1.当前使用的UReport的具体版本号：

2.2.4-SNAPSHOT

2.遇到的问题描述：

SQL条件表达式问题，SQL中增加条件表达式${(emptyparam("area")==true ? "" : " and area=:area ")} 预览数据时提示错误 “服务端错误：You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'GROUP BY area order by area' at line 4”
把表达式改成${(emptyparam("area")!=true ? "" : " and area=:area ")} 则可正常预览

3.涉及到的异常信息（完整异常信息）：
SELECT area, count(*) total, count(*) / 365 as rating FROM fact_air_cn
WHERE YEAR (dt) = '2014'  and quality = '严重污染'
 and area=:area 
GROUP BY area
order by area
十二月 15, 2017 2:11:25 下午 org.apache.catalina.core.StandardWrapperValve invoke
严重: Servlet.service() for servlet [ureportServlet] in context with path [/jreport-ureport] threw exception [javax.servlet.ServletException: java.lang.reflect.InvocationTargetException] with root cause
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'GROUP BY area
order by area' at line 4
	at sun.reflect.GeneratedConstructorAccessor17.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:409)
	at com.mysql.jdbc.Util.getInstance(Util.java:384)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4232)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4164)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2615)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2776)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2838)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2082)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2212)
	at org.springframework.jdbc.core.JdbcTemplate$1.doInPreparedStatement(JdbcTemplate.java:692)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:633)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:684)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:711)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:761)
	at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.query(NamedParameterJdbcTemplate.java:192)
	at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.queryForList(NamedParameterJdbcTemplate.java:264)
	at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.queryForList(NamedParameterJdbcTemplate.java:271)
	at com.bstek.ureport.console.designer.DatasourceServletAction.previewData(DatasourceServletAction.java:242)
	at sun.reflect.GeneratedMethodAccessor21.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.bstek.ureport.console.BaseServletAction.invokeMethod(BaseServletAction.java:77)
	at com.bstek.ureport.console.designer.DatasourceServletAction.execute(DatasourceServletAction.java:81)
	at com.bstek.ureport.console.UReportServlet.service(UReportServlet.java:81)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:436)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1078)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

4.相关截图：
![image](https://user-images.githubusercontent.com/1445707/34029168-0b0c9ec8-e1a2-11e7-8fa4-dd8be78a765c.png)
![image](https://user-images.githubusercontent.com/1445707/34029181-15dd4a8c-e1a2-11e7-8fd4-33c92d67f915.png)

**Comment by muxiaoshan** [comment]
![image](https://user-images.githubusercontent.com/1445707/34029725-eee1b438-e1a4-11e7-9a87-b24ee794d993.png)
如果给参数增加默认值，这条sql才能正常使用

**Comment by youseries** [comment]
已修复，请更新最新的2.2.4-SNAPSHOT测试，谢谢。
