### ISSUE TITLE
非Maven项目配置UReport后启动项目报错！

### ISSUE THREAD

**Issue by HyacinthDn** [youseries/ureport#146]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：
2.2.3

*  #### 遇到的问题描述：
启动项目后报错

*  #### 涉及到的异常信息（完整异常信息）：
十二月 25, 2017 10:56:33 上午 org.apache.catalina.core.StandardContext listenerStart
严重: Exception sending context initialized event to listener instance of class org.springframework.web.context.ContextLoaderListener
org.springframework.beans.factory.BeanDefinitionStoreException: Invalid bean definition with name 'ureport.fileReportProvider' defined in class path resource [ureport-core-context.xml]: Could not resolve placeholder 'ureport.fileStoreDir' in string value "${ureport.fileStoreDir}"; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'ureport.fileStoreDir' in string value "${ureport.fileStoreDir}"
	at org.springframework.beans.factory.config.PlaceholderConfigurerSupport.doProcessProperties(PlaceholderConfigurerSupport.java:211)
	at org.springframework.beans.factory.config.PropertyPlaceholderConfigurer.processProperties(PropertyPlaceholderConfigurer.java:223)
	at org.springframework.beans.factory.config.PropertyResourceConfigurer.postProcessBeanFactory(PropertyResourceConfigurer.java:86)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:265)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:162)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:606)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:462)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:403)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:106)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5068)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5584)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1572)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1562)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'ureport.fileStoreDir' in string value "${ureport.fileStoreDir}"
	at org.springframework.util.PropertyPlaceholderHelper.parseStringValue(PropertyPlaceholderHelper.java:174)
	at org.springframework.util.PropertyPlaceholderHelper.replacePlaceholders(PropertyPlaceholderHelper.java:126)
	at org.springframework.beans.factory.config.PropertyPlaceholderConfigurer$PlaceholderResolvingStringValueResolver.resolveStringValue(PropertyPlaceholderConfigurer.java:259)
	at org.springframework.beans.factory.config.BeanDefinitionVisitor.resolveStringValue(BeanDefinitionVisitor.java:282)
	at org.springframework.beans.factory.config.BeanDefinitionVisitor.resolveValue(BeanDefinitionVisitor.java:204)
	at org.springframework.beans.factory.config.BeanDefinitionVisitor.visitPropertyValues(BeanDefinitionVisitor.java:141)
	at org.springframework.beans.factory.config.BeanDefinitionVisitor.visitBeanDefinition(BeanDefinitionVisitor.java:82)
	at org.springframework.beans.factory.config.PlaceholderConfigurerSupport.doProcessProperties(PlaceholderConfigurerSupport.java:208)
	... 18 more

十二月 25, 2017 10:56:33 上午 com.baomidou.kisso.common.util.PropertiesUtil extractRunMode
信息: sso.run.mode=online_mode
十二月 25, 2017 10:56:33 上午 com.baomidou.kisso.SSOConfig init
信息: kisso init success.
十二月 25, 2017 10:56:33 上午 org.apache.catalina.core.StandardContext listenerStart
严重: Exception sending context initialized event to listener instance of class com.els.message.listener.MessageListener
org.springframework.beans.factory.BeanDefinitionStoreException: Invalid bean definition with name 'ureport.fileReportProvider' defined in class path resource [ureport-core-context.xml]: Could not resolve placeholder 'ureport.fileStoreDir' in string value "${ureport.fileStoreDir}"; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'ureport.fileStoreDir' in string value "${ureport.fileStoreDir}"
	at org.springframework.beans.factory.config.PlaceholderConfigurerSupport.doProcessProperties(PlaceholderConfigurerSupport.java:211)
	at org.springframework.beans.factory.config.PropertyPlaceholderConfigurer.processProperties(PropertyPlaceholderConfigurer.java:223)
	at org.springframework.beans.factory.config.PropertyResourceConfigurer.postProcessBeanFactory(PropertyResourceConfigurer.java:86)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:265)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:162)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:606)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:462)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:403)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:106)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5068)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5584)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1572)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1562)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'ureport.fileStoreDir' in string value "${ureport.fileStoreDir}"
	at org.springframework.util.PropertyPlaceholderHelper.parseStringValue(PropertyPlaceholderHelper.java:174)
	at org.springframework.util.PropertyPlaceholderHelper.replacePlaceholders(PropertyPlaceholderHelper.java:126)
	at org.springframework.beans.factory.config.PropertyPlaceholderConfigurer$PlaceholderResolvingStringValueResolver.resolveStringValue(PropertyPlaceholderConfigurer.java:259)
	at org.springframework.beans.factory.config.BeanDefinitionVisitor.resolveStringValue(BeanDefinitionVisitor.java:282)
	at org.springframework.beans.factory.config.BeanDefinitionVisitor.resolveValue(BeanDefinitionVisitor.java:204)
	at org.springframework.beans.factory.config.BeanDefinitionVisitor.visitPropertyValues(BeanDefinitionVisitor.java:141)
	at org.springframework.beans.factory.config.BeanDefinitionVisitor.visitBeanDefinition(BeanDefinitionVisitor.java:82)
	at org.springframework.beans.factory.config.PlaceholderConfigurerSupport.doProcessProperties(PlaceholderConfigurerSupport.java:208)
	... 18 more

十二月 25, 2017 10:56:33 上午 org.apache.catalina.core.StandardContext startInternal
严重: One or more listeners failed to start. Full details will be found in the appropriate container log file
十二月 25, 2017 10:56:33 上午 org.apache.catalina.core.StandardContext startInternal
严重: Context [/ELSServer_VOSS] startup failed due to previous errors
十二月 25, 2017 10:56:33 上午 com.baomidou.kisso.web.WebKissoConfigurer shutdownKisso
信息: Uninstalling Kisso 
十二月 25, 2017 10:56:33 上午 org.apache.catalina.core.ApplicationContext log
信息: Closing Spring root WebApplicationContext
十二月 25, 2017 10:56:33 上午 org.apache.coyote.AbstractProtocol start
信息: Starting ProtocolHandler ["http-bio-8080"]
十二月 25, 2017 10:56:33 上午 org.apache.coyote.AbstractProtocol start
信息: Starting ProtocolHandler ["ajp-bio-8009"]
十二月 25, 2017 10:56:33 上午 org.apache.catalina.startup.Catalina start
信息: Server startup in 14120 ms

*  #### 相关截图：
![image](https://user-images.githubusercontent.com/27839064/34331611-4c193016-e963-11e7-9f27-edd7d3042ddd.png)
我的配置如下：我是这样配的，我是先在web.xml中加了这个映射！
![image](https://user-images.githubusercontent.com/27839064/34331720-3a34cb3e-e964-11e7-81a1-512a7a05425a.png)
然后我又建了一个这个配置文件！
![image](https://user-images.githubusercontent.com/27839064/34331726-4e3b0490-e964-11e7-94c1-cfaf257e08df.png)

**Comment by youseries** [comment]
导致此问题的原因是你项目中也配置了spring的properties配置文件，同时默认情况下，你项目中配置的这个properties文件加载优化级较高，也就是spring会首先加载这个文件，这样在加载完这个文件后因找不到ureport中需要的属性信息所以就报错，这个spring加载properties文件机制导致，解决办法如下：

> 关于Properties文件加载
如果你是将UReport配置到一个已存在的Spring项目中，同时项目也要Spring中加载自己的Properties文件，比如通过下面的方式加载自己的Properties文件
<context:property-placeholder location="/WEB-INF/app.properties"/>
这时启动应用，我们会发现启动过程中系统会报各种属性找不到的异常，解决办法就是在上面配置中加上 ignore-unresolvable="true" 以及 order="1" 两个属性即可，其中ignore-unresolvable属性表达忽略当前配置的Properties文件中没有配置的属性，order属性值表示加载优先级，值越小，优先级越高。
当然如果你的项目中Properties文件加载是通过配置PropertyPlaceholderConfigurer为bean的方式加载，那么同样需要为这个bean添加如下两个属性，作用也是一样：
`<property name="ignoreUnresolvablePlaceholders" value="true"></property>
<property name="order" value="1"></property>`
详细描述见文档：http://wiki.bsdn.org/pages/viewpage.action?pageId=76448360
