### ISSUE TITLE
用了两个数据源，第二个数据源中的数据集没有显示出来，取数据也没有取出来，预览的时候报错，提示没有定义第二个数据集

### ISSUE THREAD

**Issue by jamson0409** [youseries/ureport#153]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：
2.2.4-SNAPSHOT

*  #### 遇到的问题描述：
用了两个数据源，第二个数据源中的数据集没有显示出来，取数据也没有取出来，预览的时候报错，提示没有定义第二个数据集

*  #### 涉及到的异常信息（完整异常信息）：
报表计算出错，错误信息如下：
com.bstek.ureport.exception.DatasetUndefinitionException: Dataset [org] not definition. 
at com.bstek.ureport.build.Context.getDatasetData(Context.java:230) 
at com.bstek.ureport.utils.DataUtils.fetchData(DataUtils.java:50) 
at com.bstek.ureport.build.aggregate.GroupAggregate.aggregate(GroupAggregate.java:38) 
at com.bstek.ureport.build.DatasetUtils.computeDatasetExpression(DatasetUtils.java:61) 
at com.bstek.ureport.build.compute.DatasetValueCompute.compute(DatasetValueCompute.java:35) 
at com.bstek.ureport.build.DataCompute.buildCellData(DataCompute.java:63) 
at com.bstek.ureport.build.Context.buildCellData(Context.java:145) 
at com.bstek.ureport.build.ReportBuilder.buildCell(ReportBuilder.java:99) 
at com.bstek.ureport.build.ReportBuilder.buildReport(ReportBuilder.java:80) 
at com.bstek.ureport.export.ReportRender.render(ReportRender.java:57) 
at com.bstek.ureport.export.ExportManagerImpl.exportHtml(ExportManagerImpl.java:46) 
at com.bstek.ureport.console.html.HtmlPreviewServletAction.loadReport(HtmlPreviewServletAction.java:318) 
at com.bstek.ureport.console.html.HtmlPreviewServletAction.execute(HtmlPreviewServletAction.java:78) 
at com.bstek.ureport.console.UReportServlet.service(UReportServlet.java:81) 
at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) 
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230) 
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) 
at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) 
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) 
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) 
at com.ecmp.core.security.filter.AbstractSecurityFilter.doFilterInternal(AbstractSecurityFilter.java:113) 
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) 
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) 
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) 
at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:167) 
at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:80) 
at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346) 
at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262) 
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) 
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) 
at com.ecmp.core.security.filter.SimpleCORSFilter.doFilterInternal(SimpleCORSFilter.java:35) 
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) 
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) 
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) 
at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197) 
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) 
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) 
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) 
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) 
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) 
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:474) 
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) 
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) 
at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:624) 
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) 
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349) 
at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:783) 
at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) 
at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:798) 
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1434) 
at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) 
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) 
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) 
at java.lang.Thread.run(Thread.java:748) 

*  #### 相关截图：
![image](https://user-images.githubusercontent.com/34023140/34350377-7548b22e-ea51-11e7-8e7a-2e1f6a3ea4db.png)
![image](https://user-images.githubusercontent.com/34023140/34350398-87f03fe6-ea51-11e7-8a15-7519753ed5fc.png)

**Comment by youseries** [comment]
不该出现这种情况，刚测了下两个数据源下数据集，是好的
