### ISSUE TITLE
内存性能的问题

### ISSUE THREAD

**Issue by aiyes** [youseries/ureport#201]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：
2.2.4

*  #### 遇到的问题描述：
一个清单报表，大概70个字段，数据源是单张表，预览数据很快，但是做到报表里就cpu100%，运行几分钟之后即OutOfMemoryError。测试数据量很小，总条数不到100条，jdk运行内存配置的是 3G。
各字段的聚合方式分别设置为分组、列表模式都没效果。

*  #### 涉及到的异常信息（完整异常信息）：
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_101]
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[?:1.8.0_101]
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048) ~[?:1.8.0_101]
	at java.lang.Class.getMethod0(Class.java:3018) ~[?:1.8.0_101]
	at java.lang.Class.getMethod(Class.java:1784) ~[?:1.8.0_101]

*  #### 相关截图：

**Comment by aiyes** [comment]
某些字段设置为“文本”、表达式时，会引起分组聚合，然后就出现上面现象

**Comment by youseries** [comment]
可以加大点内存或减少字段试试，没遇到过这样的问题。

**Comment by xuexiaoao** [comment]
遇到相同的问题
我的模板有27列数据，数据量500条时，没有问题，但是13000条时，就会报内存溢出的问题，经过测试，大概到20列数据，就会报错

**Comment by liuluyang06** [comment]
请问一下  上面的内存溢出的问题解决了吗
