### ISSUE TITLE
单元格表达式使用函数判断返回指定值报错

### ISSUE THREAD

**Issue by howell86** [youseries/ureport#216]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：
2.4

*  #### 遇到的问题描述：
单元格类型为表达式，使用pcount计算某个单元格的数量，return 必须有一个加上pcount，否则报错“java.lang.NullPointerException”
![image](https://user-images.githubusercontent.com/30722476/35024236-4e6d306a-fb79-11e7-9356-b39806cf5e91.png)

报错信息：
报表计算出错，错误信息如下：
java.lang.NullPointerException
at com.bstek.ureport.expression.model.expr.set.CellExpression.computePageCells(CellExpression.java:67)
at com.bstek.ureport.expression.model.expr.FunctionExpression.buildPageExpressionData(FunctionExpression.java:73)
at com.bstek.ureport.expression.model.expr.FunctionExpression.compute(FunctionExpression.java:54)
at com.bstek.ureport.expression.model.expr.JoinExpression.compute(JoinExpression.java:46)
at com.bstek.ureport.expression.model.expr.BaseExpression.execute(BaseExpression.java:37)
at com.bstek.ureport.expression.model.expr.ifelse.ExpressionCondition.eval(ExpressionCondition.java:47)
at com.bstek.ureport.expression.model.expr.ifelse.ExpressionConditionList.eval(ExpressionConditionList.java:41)
at com.bstek.ureport.expression.model.expr.ifelse.ElseIfExpression.conditionsEval(ElseIfExpression.java:37)
at com.bstek.ureport.expression.model.expr.ifelse.IfExpression.compute(IfExpression.java:47)
at com.bstek.ureport.expression.model.expr.BaseExpression.execute(BaseExpression.java:37)
at com.bstek.ureport.build.compute.ExpressionValueCompute.compute(ExpressionValueCompute.java:59)
at com.bstek.ureport.build.DataCompute.buildCellData(DataCompute.java:63)
at com.bstek.ureport.build.Context.buildCellData(Context.java:145)

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：

**Comment by youseries** [comment]
pcount属于分页类函数，该函数只能用于重复表头或重复表尾中，具体见文档描述。
同样给你出的版本号不存在 。

**Comment by smile2014** [comment]
https://github.com/youseries/ureport/issues/325  @youseries  您好请问这个bug是否修复了啊
