### ISSUE TITLE
打印时数据集中SQL查询出来的值为Null报错

### ISSUE THREAD

**Issue by liqiaolin520** [youseries/ureport#243]
***  #### 当前使用的UReport的具体版本号：**
2.2.5-SNAPSHOT

***  #### 遇到的问题描述：**
就是打印时查询出来的值为Null就报错

*  #### 相关截图：
查询出来有值时
![image](https://user-images.githubusercontent.com/32925394/36068805-46642eba-0f19-11e8-82e9-ea7cb03f865c.png)

查询出来时me没值时,然后往下走就会抛出ReportComputeException
![image](https://user-images.githubusercontent.com/32925394/36068861-1ae6b040-0f1a-11e8-97c6-1528c3b1a158.png)

*  #### 涉及到的异常信息（完整异常信息）：
com.bstek.ureport.exception.ReportComputeException: Function [length] parameter can not be null.
	at com.bstek.ureport.expression.function.string.StringFunction.buildString(StringFunction.java:52)
	at com.bstek.ureport.expression.function.string.LengthFunction.execute(LengthFunction.java:32)
	at com.bstek.ureport.expression.model.expr.FunctionExpression.compute(FunctionExpression.java:62)
	at com.bstek.ureport.expression.model.expr.BaseExpression.execute(BaseExpression.java:37)
	at com.bstek.ureport.expression.model.expr.JoinExpression.compute(JoinExpression.java:51)
	at com.bstek.ureport.expression.model.expr.BaseExpression.execute(BaseExpression.java:37)
	at com.bstek.ureport.expression.model.expr.FunctionExpression.compute(FunctionExpression.java:57)
	at com.bstek.ureport.expression.model.expr.BaseExpression.execute(BaseExpression.java:37)
	at com.bstek.ureport.expression.model.expr.JoinExpression.compute(JoinExpression.java:51)
	at com.bstek.ureport.expression.model.expr.BaseExpression.execute(BaseExpression.java:37)
	at com.bstek.ureport.build.compute.ExpressionValueCompute.compute(ExpressionValueCompute.java:60)
	at com.bstek.ureport.build.DataCompute.buildCellData(DataCompute.java:63)
	at com.bstek.ureport.build.Context.buildCellData(Context.java:146)
	at com.bstek.ureport.build.ReportBuilder.buildCell(ReportBuilder.java:100)
	at com.bstek.ureport.build.ReportBuilder.buildReport(ReportBuilder.java:81)
	at com.bstek.ureport.export.ReportRender.render(ReportRender.java:57)
	at com.bstek.ureport.export.ExportManagerImpl.exportHtml(ExportManagerImpl.java:47)
	at com.bstek.ureport.console.html.HtmlPreviewServletAction.loadReport(HtmlPreviewServletAction.java:317)
	at com.bstek.ureport.console.html.HtmlPreviewServletAction.execute(HtmlPreviewServletAction.java:78)
	at com.bstek.ureport.console.UReportServlet.service(UReportServlet.java:81)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1221)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61)
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1212)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1212)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:399)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:766)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:450)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:928)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:549)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:410)
	at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)

**Comment by liqiaolin520** [comment]
然后我以为只是为空这么简单，就去改了数据库的null 改成了空白，想着这总不会出事了把，没想到啊！！
![image](https://user-images.githubusercontent.com/32925394/36069004-988e33a4-0f1c-11e8-9c97-77381866007e.png)

在这里又出了事！ 我发现了一个问题，就是这里是SQL中right(MAX(meter_code_),3)
![image](https://user-images.githubusercontent.com/32925394/36069043-1824bcfa-0f1d-11e8-90be-e8cdc9efd07f.png)

原来他是做个截取的操作啊！把数据库的right操作拿到了程序中
![image](https://user-images.githubusercontent.com/32925394/36069080-ad7b201e-0f1d-11e8-9549-66d32235c458.png)

我这里是空白的，然后右边走三位变成了 -3 
data = ""
start = -3
end = 0 
所以又来了个下标越界异常！

希望Jack 你帮忙改一下把，年后把！不过希望早一点

**Comment by liqiaolin520** [comment]
刚刚天真了，我想了想也不可能把sql中的东西拿出来做截取啊！后面我看了下，问题在这
![image](https://user-images.githubusercontent.com/32925394/36069259-fb0bf9e0-0f20-11e8-82a8-d803a46ada73.png)

所以这个问题还是我的问题！

那我还是自己Close了,免得Jack哥你又说我水了！

**Comment by liqiaolin520** [comment]
字符串函数如果为null 得这样，不然空指针
![image](https://user-images.githubusercontent.com/32925394/36070697-738426d0-0f3b-11e8-8e7c-107e676227d0.png)
