### ISSUE TITLE
报表设计器重新打开含有条形码的报表时，条形码的表达式没有加载出来

### ISSUE THREAD

**Issue by zhangsean** [youseries/ureport#245]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：
v2.2.4
v2.2.5
都存在这个问题

*  #### 遇到的问题描述：
设计一个含有条形码的报表，条形码的表达式是B1，预览一切正常，就将报表保存了。
下次打开这个报表，直接预览提示失败，经过检查发现条形码的表达式是空的。
将表达式那里填写B1以后，再次预览可以正常显示条码。
再次保存报表，重新打开，发现条形码的表达式那里还是空。
检查XML文件发现表达式B1保存了，直接/ureport/preview?_u=file:.....xml预览是没有问题的。
所以只是设计器无法显示条形码的表达式的问题。

*  #### 涉及到的异常信息（完整异常信息）：
```二月 17, 2018 9:21:31 下午 org.apache.catalina.core.StandardWrapperValve invoke
严重: Servlet.service() for servlet [ureportServlet] in context with path [] threw exception [javax.servlet.ServletException: java.lang.reflect.InvocationTargetException] with root cause
com.bstek.ureport.exception.ReportParseException: Unknow context :[64]
        at com.bstek.ureport.expression.parse.ExpressionVisitor.parseExprComposite(ExpressionVisitor.java:172)
        at com.bstek.ureport.expression.parse.ExpressionVisitor.visitExpression(ExpressionVisitor.java:75)
        at com.bstek.ureport.expression.ExpressionUtils.parseExpression(ExpressionUtils.java:139)
        at com.bstek.ureport.parser.impl.value.ZxingValueParser.parse(ZxingValueParser.java:59)
        at com.bstek.ureport.parser.impl.value.ZxingValueParser.parse(ZxingValueParser.java:31)
        at com.bstek.ureport.parser.impl.CellParser.parseValue(CellParser.java:140)
        at com.bstek.ureport.parser.impl.CellParser.parse(CellParser.java:108)
        at com.bstek.ureport.parser.impl.CellParser.parse(CellParser.java:49)
        at com.bstek.ureport.parser.ReportParser.parse(ReportParser.java:89)
        at com.bstek.ureport.console.designer.DesignerServletAction.savePreviewData(DesignerServletAction.java:122)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at com.bstek.ureport.console.BaseServletAction.invokeMethod(BaseServletAction.java:79)
        at com.bstek.ureport.console.designer.DesignerServletAction.execute(DesignerServletAction.java:65)
        at com.bstek.ureport.console.UReportServlet.service(UReportServlet.java:81)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:100)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:953)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1041)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:603)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
```

*  #### 相关截图：
![issue1](https://user-images.githubusercontent.com/2536402/36341682-ce0ad2d4-142c-11e8-9487-73ae615ee385.png)
![issue2](https://user-images.githubusercontent.com/2536402/36341684-d6927704-142c-11e8-8156-34393e6b42b5.png)

[固定行数分页.ureport.zip](https://github.com/youseries/ureport/files/1733722/ureport.zip)

**Comment by youseries** [comment]
BUG，最新版SNAPSHOT中已修复，谢谢。
