### ISSUE TITLE
左父格与单元格的合并

### ISSUE THREAD

**Issue by jjianhang** [youseries/ureport#264]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：
<dependency>
            <groupId>com.bstek.ureport</groupId>
            <artifactId>ureport2-console</artifactId>
            <version>2.2.4</version>
</dependency>

*  #### 遇到的问题描述：
有A、B、C、D、E五列
当A、B列聚合方式为分组，C列为count()，
当D列左父格为C时，报错：Report cells has cyclic dependency. ；
当D列左父格为B时，C列count（）出的数据列无法合并行；
当D列左父格为A时，B列的分组失效。
我想要[B]的左父格为 [A] ;   C，D的左父格为B，并且C的行也合并

*  #### 涉及到的异常信息（完整异常信息）：
报表计算出错，错误信息如下：
com.bstek.ureport.exception.CellDependencyException: Report cells has cyclic dependency. 
at com.bstek.ureport.build.Context.nextUnprocessedCells(Context.java:263) 
at com.bstek.ureport.build.ReportBuilder.buildCell(ReportBuilder.java:94) 
at com.bstek.ureport.Utils.fetchTargetCells(Utils.java:85) 
at com.bstek.ureport.expression.model.expr.set.CellExpression.compute(CellExpression.java:48) 
at com.bstek.ureport.expression.model.expr.BaseExpression.execute(BaseExpression.java:37) 
at com.bstek.ureport.expression.model.expr.FunctionExpression.compute(FunctionExpression.java:57) 
at com.bstek.ureport.expression.model.expr.JoinExpression.compute(JoinExpression.java:46) 
at com.bstek.ureport.expression.model.expr.BaseExpression.execute(BaseExpression.java:37) 
at com.bstek.ureport.build.compute.ExpressionValueCompute.compute(ExpressionValueCompute.java:60) 
at com.bstek.ureport.build.DataCompute.buildCellData(DataCompute.java:63) 
at com.bstek.ureport.build.Context.buildCellData(Context.java:146) 
at com.bstek.ureport.build.ReportBuilder.buildCell(ReportBuilder.java:100) 
at com.bstek.ureport.Utils.fetchTargetCells(Utils.java:85) 
at com.bstek.ureport.expression.model.expr.set.CellExpression.compute(CellExpression.java:48) 
at com.bstek.ureport.expression.model.expr.BaseExpression.execute(BaseExpression.java:37) 
at com.bstek.ureport.expression.model.expr.FunctionExpression.compute(FunctionExpression.java:57) 
at com.bstek.ureport.expression.model.expr.JoinExpression.compute(JoinExpression.java:46) 
at com.bstek.ureport.expression.model.expr.BaseExpression.execute(BaseExpression.java:37) 
at com.bstek.ureport.build.compute.ExpressionValueCompute.compute(ExpressionValueCompute.java:60) 
at com.bstek.ureport.build.DataCompute.buildCellData(DataCompute.java:63) 
at com.bstek.ureport.build.Context.buildCellData(Context.java:146) 
at com.bstek.ureport.build.ReportBuilder.buildCell(ReportBuilder.java:100) 
at com.bstek.ureport.build.ReportBuilder.buildReport(ReportBuilder.java:81) 
at com.bstek.ureport.console.html.HtmlPreviewServletAction.loadReport(HtmlPreviewServletAction.java:286) 
at com.bstek.ureport.console.html.HtmlPreviewServletAction.execute(HtmlPreviewServletAction.java:78) 
at com.bstek.ureport.console.UReportServlet.service(UReportServlet.java:81) 
at javax.servlet.http.HttpServlet.service(HttpServlet.java:731) 
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303) 
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) 
at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) 
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) 
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) 
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220) 
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122) 
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505) 
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170) 
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103) 
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116) 
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423) 
at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079) 
at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:620) 
at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2476) 
at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2465) 
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) 
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) 
at java.lang.Thread.run(Thread.java:724) 

 

*  #### 相关截图：
![zfg1](https://user-images.githubusercontent.com/37208277/37448116-e2e42240-285f-11e8-95b1-dbb212261d94.png)
![zfg](https://user-images.githubusercontent.com/37208277/37448121-e89299ec-285f-11e8-9a12-89a543e861f7.png)

**Comment by youseries** [comment]
`com.bstek.ureport.exception.CellDependencyException: Report cells has cyclic dependency.`
异常很清楚，你配置存在单元格父格的循环依赖问题，这需要你自己检查，帮不了你。

**Comment by jjianhang** [comment]
@youseries 我想要[B]和【C】的左父格都为【A】，并且[B],[C】都分组显示，这个能解决么
