### ISSUE TITLE
formatdate()只能传入一个参数bug

### ISSUE THREAD

**Issue by tankxxl** [youseries/ureport#283]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：
2.2.6

*  #### 遇到的问题描述：
在使用formatdate()函数时，只能传入一个参数才能使用，如果传入两个参数就会报异常，也即：
只能formatdate(C1)这样使用，而不能formatdate(C1,"yyyyMMdd")这样使用。
通过debug发现源码有bug。

*  #### 涉及到的异常信息（完整异常信息）：
报表计算出错，错误信息如下：
com.bstek.ureport.exception.ReportComputeException: Function [formatdate] first parameter is Date type
at com.bstek.ureport.expression.function.FormatDateFunction.execute(FormatDateFunction.java:74)
at com.bstek.ureport.expression.model.expr.FunctionExpression.compute(FunctionExpression.java:62)
at com.bstek.ureport.expression.model.expr.JoinExpression.compute(JoinExpression.java:46)
at com.bstek.ureport.expression.model.expr.BaseExpression.execute(BaseExpression.java:37)
at com.bstek.ureport.build.compute.ExpressionValueCompute.compute(ExpressionValueCompute.java:60)
at com.bstek.ureport.build.DataCompute.buildCellData(DataCompute.java:63)
at com.bstek.ureport.build.Context.buildCellData(Context.java:146)
at com.bstek.ureport.build.ReportBuilder.buildCell(ReportBuilder.java:100)
at com.bstek.ureport.build.ReportBuilder.buildReport(ReportBuilder.java:81)
at com.bstek.ureport.console.html.HtmlPreviewServletAction.loadReport(HtmlPreviewServletAction.java:279)
at com.bstek.ureport.console.html.HtmlPreviewServletAction.execute(HtmlPreviewServletAction.java:78)
at com.bstek.ureport.console.UReportServlet.service(UReportServlet.java:81)

*  #### 相关截图：
![image](https://user-images.githubusercontent.com/1826540/38535598-d1205f0e-3cb6-11e8-9670-54fed610a0fb.png)
![image](https://user-images.githubusercontent.com/1826540/38535713-71727e60-3cb7-11e8-90f1-7ccddcb73630.png)

**Comment by youseries** [comment]
formatdate函数要求第一个参数值必须是一个日期类型对象，你给你的不是，所以导致报错。
