### ISSUE TITLE
在IE下查看报表后台报Invalid character found in the request target.The valid characters are define

### ISSUE THREAD

**Issue by github568219115** [youseries/ureport#284]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：
2.0.5

*  #### 遇到的问题描述：
当报表的名称是中文时，在IE10下分页查看时报错
比如URL为http://xxxx:8080/report/ureport/preview?_u=test:订单.ureport.xml&_i=1&
通过分页预览时，后台就会报异常，前台返回400错误

*  #### 涉及到的异常信息（完整异常信息）：
java.lang.IllegalArgumentException: Invalid character found in the request target. The valid characters are defined in RFC 7230 and RFC 3986
	at org.apache.coyote.http11.AbstractNioInputBuffer.parseRequestLine(AbstractNioInputBuffer.java:285)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1045)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:684)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1539)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1495)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

*  #### 相关截图：

**Comment by youseries** [comment]
版本太低，升级到最新版
