### ISSUE TITLE
内置数据源查询数据可以，添加之后提示加载字段失败!

### ISSUE THREAD

**Issue by houybBj** [youseries/ureport#285]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：

ureport2-console-2.0.0

*  #### 遇到的问题描述：

![qq 20180412162852](https://user-images.githubusercontent.com/20568617/38665316-ae25f73e-3e6e-11e8-9b39-12c42e2a2420.jpg)

*  #### 涉及到的异常信息（完整异常信息）：
四月 12, 2018 4:27:59 下午 org.apache.catalina.core.StandardWrapperValve invoke
严重: Servlet.service() for servlet ureportServlet threw exception
com.bstek.ureport.console.exception.ReportDesignException: Buildin datasource [????????°??????] not exist.
	at com.bstek.ureport.console.designer.DatasourceServletAction.buildConnection(DatasourceServletAction.java:300)
	at com.bstek.ureport.console.designer.DatasourceServletAction.buildFields(DatasourceServletAction.java:153)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.bstek.ureport.console.BaseServletAction.invokeMethod(BaseServletAction.java:74)
	at com.bstek.ureport.console.designer.DatasourceServletAction.execute(DatasourceServletAction.java:68)
	at com.bstek.ureport.console.UReportServlet.service(UReportServlet.java:76)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:803)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:230)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:175)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:128)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:104)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:261)
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:844)
	at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:581)
	at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:447)
	at java.lang.Thread.run(Thread.java:744)

*  #### 相关截图：

**Comment by youseries** [comment]
版本太低，升级到最新版。
