### ISSUE TITLE
配置条件熟悉报异常

### ISSUE THREAD

**Issue by peterjiao88** [youseries/ureport#290]
版本号2.26
报表计算出错，错误信息如下：
java.lang.NullPointerException
at com.bstek.ureport.build.HideRowColumnBuilder.doHideProcessRow(HideRowColumnBuilder.java:116)
at com.bstek.ureport.build.Context.doHideProcessRow(Context.java:115)
at com.bstek.ureport.model.Cell.doComputeConditionProperty(Cell.java:334)
at com.bstek.ureport.model.Cell.doCompute(Cell.java:257)
at com.bstek.ureport.build.ReportBuilder.recomputeCells(ReportBuilder.java:310)
at com.bstek.ureport.build.ReportBuilder.buildReport(ReportBuilder.java:85)
at com.bstek.ureport.console.html.HtmlPreviewServletAction.loadReport(HtmlPreviewServletAction.java:279)
at com.bstek.ureport.console.html.HtmlPreviewServletAction.execute(HtmlPreviewServletAction.java:78)
at com.bstek.ureport.console.UReportServlet.service(UReportServlet.java:81)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:85)
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790)
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
at java.lang.Thread.run(Thread.java:722)
我判断一个字符串==“”时，报这个异常，为啥我传了“”还是报异常

**Comment by peterjiao88** [comment]
![default](https://user-images.githubusercontent.com/16682360/39103340-c3703fc0-46dc-11e8-8b40-b996396012ea.png)
配置条件xl=="",是设置行高等于0就会报异常，好多条件都是一样都报这个异常
![default](https://user-images.githubusercontent.com/16682360/39103387-0774694e-46dd-11e8-8bd1-0b722a71dbba.png)

**Comment by youseries** [comment]
"配置条件xl=="",是设置行高等于0就会报异常"，这里的行高是在哪里设置的？

**Comment by peterjiao88** [comment]
![default](https://user-images.githubusercontent.com/16682360/39111327-4cfd542e-4707-11e8-80e5-de5140a93b25.png)
