### ISSUE TITLE
添加表达式报异常

### ISSUE THREAD

**Issue by peterjiao88** [youseries/ureport#293]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：2.26

*  #### 遇到的问题描述：添加表达式报循环依赖异常
![default](https://user-images.githubusercontent.com/16682360/39177736-aaffc972-47e2-11e8-9689-6c2da14a2284.png)

*  #### 涉及到的异常信息（完整异常信息）：
com.bstek.ureport.exception.CellDependencyException: Report cells has cyclic dependency.
	at com.bstek.ureport.build.Context.nextUnprocessedCells(Context.java:263)
	at com.bstek.ureport.build.ReportBuilder.buildCell(ReportBuilder.java:94)
	at com.bstek.ureport.Utils.fetchTargetCells(Utils.java:85)
	at com.bstek.ureport.expression.model.expr.set.CellExpression.compute(CellExpression.java:48)
	at com.bstek.ureport.expression.model.expr.JoinExpression.compute(JoinExpression.java:46)
	at com.bstek.ureport.expression.model.expr.BaseExpression.execute(BaseExpression.java:37)
	at com.bstek.ureport.expression.model.expr.ifelse.ExpressionCondition.eval(ExpressionCondition.java:47)
	at com.bstek.ureport.expression.model.expr.ifelse.ExpressionConditionList.eval(ExpressionConditionList.java:37)
	at com.bstek.ureport.expression.model.expr.ifelse.IfExpression.compute(IfExpression.java:40)
	at com.bstek.ureport.expression.model.expr.BaseExpression.execute(BaseExpression.java:37)
	at com.bstek.ureport.build.compute.ExpressionValueCompute.compute(ExpressionValueCompute.java:60)
	at com.bstek.ureport.build.DataCompute.buildCellData(DataCompute.java:63)
	at com.bstek.ureport.build.Context.buildCellData(Context.java:146)
	at com.bstek.ureport.build.ReportBuilder.buildCell(ReportBuilder.java:100)
	at com.bstek.ureport.build.ReportBuilder.buildReport(ReportBuilder.java:81)
	at com.bstek.ureport.export.ReportRender.render(ReportRender.java:57)
	at com.bstek.ureport.export.ExportManagerImpl.exportHtml(ExportManagerImpl.java:47)
	at com.bstek.ureport.console.html.HtmlPreviewServletAction.loadReport(HtmlPreviewServletAction.java:317)
	at com.bstek.ureport.console.html.HtmlPreviewServletAction.execute(HtmlPreviewServletAction.java:78)
	at com.bstek.ureport.console.UReportServlet.service(UReportServlet.java:81)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:85)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:722)

*  #### 相关截图：
![default](https://user-images.githubusercontent.com/16682360/39177689-81fc15da-47e2-11e8-9af0-8bf5cba357ee.png)

**Comment by peterjiao88** [comment]
图片没发全
![default](https://user-images.githubusercontent.com/16682360/39177924-13eb4b00-47e3-11e8-8b39-5baf642c7215.png)

**Comment by youseries** [comment]
“com.bstek.ureport.exception.CellDependencyException: Report cells has cyclic dependency.”
提示的很清楚了，当前存在单元格循环依赖，请检查你的父格配置情况。
