### ISSUE TITLE
表达式拼接SQL时，预览方法decode的“+”号问题

### ISSUE THREAD

**Issue by shenzitao** [youseries/ureport#295]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：
**2.2.8-SNAPSHOT**

*  #### 遇到的问题描述：
报表设计器数据集的SQL使用表达式时，设计器预览的时候，
DesignerServletAction.savePreviewData 方法会把表达式里面拼接SQL的“+”号decode掉，
导致SQL解析异常。
假如去掉decode，又出现dom4j解析错误。

估计需要在前端加encode。

*  #### 涉及到的异常信息（完整异常信息）：

`com.bstek.ureport.exception.ReportParseException: Expression parse error:[[@3,658:658='(',<26>,27:0]] is invalid:mismatched input '(' expecting {<EOF>, 'to', Operator}
	at com.bstek.ureport.expression.ExpressionUtils.parseExpression(ExpressionUtils.java:142)
	at com.bstek.ureport.parser.impl.DatasourceParser.parseSql(DatasourceParser.java:141)
	at com.bstek.ureport.parser.impl.DatasourceParser.parseDatasets(DatasourceParser.java:80)
	at com.bstek.ureport.parser.impl.DatasourceParser.parse(DatasourceParser.java:52)
	at com.bstek.ureport.parser.impl.DatasourceParser.parse(DatasourceParser.java:41)
	at com.bstek.ureport.parser.ReportParser.parse(ReportParser.java:89)
	at com.bstek.ureport.console.designer.DesignerServletAction.savePreviewData(DesignerServletAction.java:123)`

去掉 decode：
`org.dom4j.DocumentException: Error on line 1 of document  : 前言中不允许有内容。 Nested exception: 前言中不允许有内容。
	at org.dom4j.io.SAXReader.read(SAXReader.java:482)
	at org.dom4j.io.SAXReader.read(SAXReader.java:343)
	at com.bstek.ureport.parser.ReportParser.parse(ReportParser.java:69)
	at com.bstek.ureport.console.designer.DesignerServletAction.savePreviewData(DesignerServletAction.java:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.bstek.ureport.console.BaseServletAction.invokeMethod(BaseServletAction.java:77)
	at com.bstek.ureport.console.designer.DesignerServletAction.execute(DesignerServletAction.java:65)
	at com.bstek.ureport.console.UReportServlet.service(UReportServlet.java:81)`
*  #### 相关截图：
![qq 01](https://user-images.githubusercontent.com/5283287/39281979-1167c66c-493a-11e8-9065-cf456bbd51b8.jpg)

![qq 011](https://user-images.githubusercontent.com/5283287/39282082-7b85a3a2-493a-11e8-906b-43b19861ecc3.jpg)

![qq 02](https://user-images.githubusercontent.com/5283287/39282127-a08763d4-493a-11e8-8cf8-c15ad2bd21df.jpg)

![qq 021](https://user-images.githubusercontent.com/5283287/39282128-a25b5634-493a-11e8-8381-51abc9e0f01c.jpg)

**Comment by youseries** [comment]
最新版2.2.8-snapshot已处理

**Comment by shenzitao** [comment]
非常感谢
