### ISSUE TITLE
 PDF在线打印报错，

### ISSUE THREAD

**Issue by ghostman-git** [youseries/ureport#316]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：
v2.2.5

*  #### 遇到的问题描述：
com.itextpdf.text.DocumentException: java.lang.IllegalArgumentException: Font size too small: 0.0
	at com.itextpdf.text.pdf.PdfDocument.add(PdfDocument.java:820)
	at com.itextpdf.text.Document.add(Document.java:277)
	at com.bstek.ureport.export.pdf.PdfProducer.produce(PdfProducer.java:196)
	at com.bstek.ureport.console.pdf.ExportPdfServletAction.buildPdf(ExportPdfServletAction.java:89)
	at com.bstek.ureport.console.pdf.ExportPdfServletAction.execute(ExportPdfServletAction.java:58)
	at com.bstek.ureport.console.UReportServlet.service(UReportServlet.java:81)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:85)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:123)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.__invoke(StandardContextValve.java:96)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:40002)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:496)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Font size too small: 0.0
	at com.itextpdf.text.pdf.PdfContentByte.setFontAndSize(PdfContentByte.java:1968)
	at com.itextpdf.text.pdf.PdfDocument.writeLineToContent(PdfDocument.java:1749)
	at com.itextpdf.text.pdf.ColumnText.go(ColumnText.java:1160)
	at com.itextpdf.text.pdf.ColumnText.go(ColumnText.java:993)
	at com.itextpdf.text.pdf.ColumnText.go(ColumnText.java:981)
	at com.itextpdf.text.pdf.PdfPRow.writeCells(PdfPRow.java:582)
	at com.itextpdf.text.pdf.PdfPTable.writeSelectedRows(PdfPTable.java:828)
	at com.itextpdf.text.pdf.PdfPTable.writeSelectedRows(PdfPTable.java:961)
	at com.itextpdf.text.pdf.ColumnText.goComposite(ColumnText.java:1983)
	at com.itextpdf.text.pdf.ColumnText.go(ColumnText.java:999)
	at com.itextpdf.text.pdf.ColumnText.go(ColumnText.java:993)
	at com.itextpdf.text.pdf.ColumnText.go(ColumnText.java:981)
	at com.itextpdf.text.pdf.PdfDocument.addPTable(PdfDocument.java:2716)
	at com.itextpdf.text.pdf.PdfDocument.add(PdfDocument.java:758)
	... 36 more

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：

**Comment by youseries** [comment]
`com.itextpdf.text.DocumentException: java.lang.IllegalArgumentException: Font size too small: 0.0`
异常提示的很清楚了，检查下你是不是有存在把字体设置为0的情况。
