### ISSUE TITLE
2.2.6 聚合平均值 异常

### ISSUE THREAD

**Issue by lbj2049** [youseries/ureport#319]
*  #### 当前使用的UReport的具体版本号：2.2.6
*  #### 遇到的问题描述：

当报表未查到数是，avg函数报错

*  #### 涉及到的异常信息（完整异常信息）：
java.lang.ArithmeticException: / by zero
	at java.math.BigDecimal.divideAndRound(BigDecimal.java:4106)
	at java.math.BigDecimal.divide(BigDecimal.java:5183)
	at java.math.BigDecimal.divide(BigDecimal.java:1561)
	at com.bstek.ureport.build.aggregate.AvgAggregate.buildAvg(AvgAggregate.java:130)
	at com.bstek.ureport.build.aggregate.AvgAggregate.aggregate(AvgAggregate.java:53)
	at com.bstek.ureport.build.DatasetUtils.computeDatasetExpression(DatasetUtils.java:61)
	at com.bstek.ureport.build.compute.DatasetValueCompute.compute(DatasetValueCompute.java:35)
	at com.bstek.ureport.build.DataCompute.buildCellData(DataCompute.java:63)
	at com.bstek.ureport.build.Context.buildCellData(Context.java:146)
	at com.bstek.ureport.build.ReportBuilder.buildCell(ReportBuilder.java:100)
	at com.bstek.ureport.build.ReportBuilder.buildReport(ReportBuilder.java:81)
	at com.bstek.ureport.export.ReportRender.render(ReportRender.java:57)
	at com.bstek.ureport.export.ExportManagerImpl.exportHtml(ExportManagerImpl.java:47)

**Comment by youseries** [comment]
异常提示很明确了：
java.lang.ArithmeticException: / by zero
因为没有数据导致除0操作异常。
