### ISSUE TITLE
单元格属性设置过滤条件包含%导致报表打不开

### ISSUE THREAD

**Issue by DuaneDu** [youseries/ureport#329]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：
2.2.8

*  #### 遇到的问题描述：
包含%导致报表文件打不开

*  #### 涉及到的异常信息（完整异常信息）：
line 1:2 no viable alternative at input '\<EOF\>'
com.bstek.ureport.exception.ReportParseException: Expression parse error:[[@2,2:1='\<EOF\>',<-1>,1:2]] is invalid:no viable alternative at input '\<EOF\>'

	at com.bstek.ureport.expression.ExpressionUtils.parseExpression(ExpressionUtils.java:118)
	at com.bstek.ureport.parser.impl.value.DatasetValueParser.parseCondition(DatasetValueParser.java:138)
	at com.bstek.ureport.parser.impl.value.DatasetValueParser.parse(DatasetValueParser.java:70)
	at com.bstek.ureport.parser.impl.value.DatasetValueParser.parse(DatasetValueParser.java:40)
	at com.bstek.ureport.parser.impl.CellParser.parseValue(CellParser.java:131)
	at com.bstek.ureport.parser.impl.CellParser.parse(CellParser.java:99)
	at com.bstek.ureport.parser.impl.CellParser.parse(CellParser.java:38)
	at com.bstek.ureport.parser.ReportParser.parse(ReportParser.java:76)

*  #### 相关截图：
![image](https://user-images.githubusercontent.com/17942048/42074735-29ec97ba-7ba0-11e8-8bce-9d6c594c47d3.png)

**Comment by youseries** [comment]
试试最新的2.2.9-SNAPSHOT。

**Comment by DuaneDu** [comment]
问题已经验证.依然存在

**Comment by youseries** [comment]
是你用法不对，条件中的值是一个表达式，需要用单引号或双引号包裹，你这样肯定不对，而且Like比较不支持%，这里不是SQL.
