### ISSUE TITLE
表达式正确，报出了java.lang.NullPointerException异常

### ISSUE THREAD

**Issue by bigliangcong** [youseries/ureport#338]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：2.2.8

*  #### 遇到的问题描述：
我的表达式  GQKCSJ.sum(YCJKC,CUSTOM3 == 'IHVOCDU' and  emptyparam("CUSTOM3")==false)

*  #### 涉及到的异常信息（完整异常信息）：
报表计算出错，错误信息如下：
java.lang.NullPointerException 
at com.bstek.ureport.expression.model.condition.CellExpressionCondition.computeLeft(CellExpressionCondition.java:41) 
at com.bstek.ureport.expression.model.condition.BaseCondition.filter(BaseCondition.java:48) 
at com.bstek.ureport.build.aggregate.SumAggregate.buildSum(SumAggregate.java:112) 
at com.bstek.ureport.build.aggregate.SumAggregate.aggregate(SumAggregate.java:53) 
at com.bstek.ureport.build.DatasetUtils.computeDatasetExpression(DatasetUtils.java:61) 
at com.bstek.ureport.expression.model.expr.dataset.DatasetExpression.compute(DatasetExpression.java:74) 
at com.bstek.ureport.expression.model.expr.JoinExpression.compute(JoinExpression.java:46) 
at com.bstek.ureport.expression.model.expr.BaseExpression.execute(BaseExpression.java:37) 
at com.bstek.ureport.build.compute.ExpressionValueCompute.compute(ExpressionValueCompute.java:60) 
at com.bstek.ureport.build.DataCompute.buildCellData(DataCompute.java:63) 
at com.bstek.ureport.build.Context.buildCellData(Context.java:146) 
at com.bstek.ureport.build.ReportBuilder.buildCell(ReportBuilder.java:100) 
at com.bstek.ureport.build.ReportBuilder.buildReport(ReportBuilder.java:81) 
at com.bstek.ureport.console.html.HtmlPreviewServletAction.loadReport(HtmlPreviewServletAction.java:279) 
at com.bstek.ureport.console.html.HtmlPreviewServletAction.execute(HtmlPreviewServletAction.java:78) 
at com.bstek.ureport.console.UReportServlet.service(UReportServlet.java:81) 
at javax.servlet.http.HttpServlet.service(HttpServlet.java:731) 
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303) 
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) 
at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) 
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) 
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) 
at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88) 
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) 
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) 
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) 
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220) 
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122) 
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505) 
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170) 
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103) 
at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956) 
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116) 
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423) 
at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079) 
at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625) 
at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318) 
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) 
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) 
at java.lang.Thread.run(Thread.java:745) 
 

*  #### 相关截图：
![image](https://user-images.githubusercontent.com/28283553/43238677-c54a1c24-90c1-11e8-844a-b5e05246ea38.png)
![image](https://user-images.githubusercontent.com/28283553/43238694-d6dc7d74-90c1-11e8-8dd7-7a268d680f33.png)

**Comment by youseries** [comment]
刚本地测了下，同样的表达式：emp.sum(salary,dept_id=='D21' and emptyparam("DD")==true)，没有问题。

**Comment by bigliangcong** [comment]
已经解决了，三克油
------------------------------------------------------------------
发件人：高杰 <notifications@github.com>
发送时间：2018年8月1日(星期三) 12:00
收件人：youseries/ureport <ureport@noreply.github.com>
抄　送：梁聪 <liangcong@z-try.com>; Author <author@noreply.github.com>
主　题：Re: [youseries/ureport] 表达式正确，报出了java.lang.NullPointerException异常 (#338)

刚本地测了下，同样的表达式：emp.sum(salary,dept_id=='D21' and emptyparam("DD")==true)，没有问题。
