### ISSUE TITLE
表达式解析的bug

### ISSUE THREAD

**Issue by github568219115** [youseries/ureport#362]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：

2.3.0-SNAPSHOT

*  #### 遇到的问题描述：
在制作环比报表时，填写表达式‘C1-C1[A1:-1]’，后台报错，但是如果表达式写成‘C1 -C1[A1:-1]’这样就不报错，也就是‘C1’与‘-C1[A1:-1]’之间一定有个空格才不会报错

*  #### 涉及到的异常信息（完整异常信息）：

line 1:5 extraneous input '[' expecting {<EOF>, 'case', 'if', 'return', 'var', '&', '$', '#', 'cell', Cell, Operator, BOOLEAN, 'null', '(', STRING, INTEGER, NUMBER, Identifier}
line 1:9 no viable alternative at input 'A1:-1'
com.bstek.ureport.exception.ReportParseException: Expression [] is invalid.
	at com.bstek.ureport.expression.parse.ExpressionVisitor.visitExpression(ExpressionVisitor.java:118)
	at com.bstek.ureport.expression.parse.ExpressionVisitor.visitEntry(ExpressionVisitor.java:85)
	at com.bstek.ureport.expression.ExpressionUtils.parseExpression(ExpressionUtils.java:141)
	at com.bstek.ureport.definition.value.ExpressionValue.<init>(ExpressionValue.java:30)
	at com.bstek.ureport.parser.impl.value.ExpressionValueParser.parse(ExpressionValueParser.java:29)
	at com.bstek.ureport.parser.impl.value.ExpressionValueParser.parse(ExpressionValueParser.java:1)
	at com.bstek.ureport.parser.impl.CellParser.parseValue(CellParser.java:140)
	at com.bstek.ureport.parser.impl.CellParser.parse(CellParser.java:108)
	at com.bstek.ureport.parser.impl.CellParser.parse(CellParser.java:1)
	at com.bstek.ureport.parser.ReportParser.parse(ReportParser.java:89)
	at com.bstek.ureport.console.designer.DesignerServletAction.savePreviewData(DesignerServletAction.java:123)

*  #### 相关截图：

**Comment by youseries** [comment]
不算bug，减号前后要有空格。
