### ISSUE TITLE
sql like 传参问题

### ISSUE THREAD

**Issue by liushengchao** [youseries/ureport#397]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：
2.2.9

*  #### 遇到的问题描述：

表头上文本框绑定的参数传递错误

*  #### 涉及到的异常信息（完整异常信息）：
 位置：876]; SQL was [SELECT fg.product_id,pd.pseudo_id,pd.product_name,fg.design_number,fg.customer_product_aliases,fg.pattern_type_enum_id,fg.clothing_series_enum_id,fg.clothing_brand_enum_id,fg.season_enum_id,fg.clothing_category_id,fg.fabric_category_id,pc.content_location,ov.product_status_id,ov.product_opt_user_id,ov.product_opt_stamp,ov.design_bom_opt_user_id,ov.design_bom_status_id,ov.design_bom_opt_stamp,pattern_status_id,ov.pattern_opt_user_id,ov.pattern_opt_stamp,routing_work_effort_status_id,ov.routing_work_effort_opt_user_id,ov.routing_work_effort_opt_stamp,ie_status_id,ov.ie_opt_user_id,ov.ie_opt_stamp FROM finished_good fg LEFT JOIN common_biz_status_over_view ov ON fg.product_id = ov.product_id left join product pd on pd.product_id = ov.product_id LEFT JOIN product_content pc ON pc.product_id = fg.product_id where ov.product_id is not NULL   AND design_number like '%' ? '%' GROUP BY ov.product_id,fg.product_id,pd.product_id,pc.content_location] for task [PreparedStatementCallback]
2018-10-26 18:54:01.967:WARN:oejs.HttpChannel:qtp1865127310-1424: /ureport/preview/loadData
javax.servlet.ServletException: javax.servlet.ServletException: java.lang.reflect.InvocationTargetException
	at com.bstek.ureport.console.UReportServlet.service(UReportServlet.java:93)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:865)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1655)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:215)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.ebaysf.web.cors.CORSFilter.handleSimpleCORS(CORSFilter.java:302)
	at org.ebaysf.web.cors.CORSFilter.doFilter(CORSFilter.java:160)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1634)
	at org.moqui.elasticsearch.ElasticRequestLogFilter.doFilter(ElasticRequestLogFilter.groovy:101)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1340)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1242)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:690)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:503)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)

*  #### 相关截图：
![issue](https://user-images.githubusercontent.com/16935020/47562485-35068c00-d951-11e8-81ad-3be60720a38c.png)

**Comment by dume2007** [comment]
参考sql：
`${
"select id,account,name,phone,FROM_UNIXTIME(create_time, \'%Y-%m-%d\') AS create_day
from xm_users where 1=1"
+(param("create_date")!=null && param("create_date")!="" ? " and create_time >= UNIX_TIMESTAMP(:create_date)" : "")
+(param("end_create_date")!=null && param("end_create_date")!="" ? " and create_time <= UNIX_TIMESTAMP(:end_create_date)" : "")
+(param("name")!=null && param("name")!="" ? " and name Like CONCAT(:name, \'%\')" : "")
+" order by id desc limit 50"
}`

亲测可行
