### ISSUE TITLE
数据集单元格分组排序时IllegalArgumentException

### ISSUE THREAD

**Issue by hug3id** [youseries/ureport#399]
*  #### 当前使用的UReport的具体版本号：2.2.9

*  #### 遇到的问题描述：

当字段数据中存在null，排序时有可能出现 IllegalArgumentException 异常

*  #### 涉及到的异常信息（完整异常信息）：
java.lang.IllegalArgumentException: Comparison method violates its general contract!
at java.util.TimSort.mergeLo(TimSort.java:777)
at java.util.TimSort.mergeAt(TimSort.java:514)
at java.util.TimSort.mergeCollapse(TimSort.java:441)
at java.util.TimSort.sort(TimSort.java:245)
at java.util.Arrays.sort(Arrays.java:1512)
at java.util.ArrayList.sort(ArrayList.java:1462)
at java.util.Collections.sort(Collections.java:175)
at com.bstek.ureport.build.aggregate.Aggregate.orderBindDataList(Aggregate.java:73)

*  #### 原因分析：
原因是JDK7以后Collections.sort使用了Timesort算法，因此实现Comparable接口时，要满足一下三个特性：
1） 自反性：x，y 的比较结果和 y，x 的比较结果相反。
2） 传递性：x>y,y>z,则 x>z。
3） 对称性：x=y,则 x,z 比较结果和 y，z 比较结果相同。

Aggregate.java第73行开始：
Collections.sort(list, new Comparator<BindData>() {
  @Override
  public int compare(BindData o1, BindData o2) {
    Object data1=o1.getValue();
    Object data2=o2.getValue();
    if(data1==null || data2==null){
      return 1; // 不符合以上规则
    }

因此需要将null判断修改为（设定null最小）：
if (data1 == null) {
    if (data2 == null) {
        return 0;
    }
    return -1;
}
else if (data2 == null) {
    return 1;
}

**Comment by hug3id** [comment]
同样的问题还有 OrderFunction.java
