### ISSUE TITLE
实现自定义存储器，点击保存时报错：getOutputStream() has already been called for this response

### ISSUE THREAD

**Issue by zsplatzangy** [youseries/ureport#439]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：
2.2.9

*  #### 遇到的问题描述：
实现ReportProvider接口，增加自定义报表存储器，将报表文件保存至数据库。
项目可以正常启动，但是点击保存时，后端报错，并且继续保存，页面会提示“请选择文件保存地！”
项目环境：
JDK1.8
SpringBoot 1.5.3.RELEASE
Mybatis 1.3.2

*  #### 涉及到的异常信息（完整异常信息）：
`java.lang.IllegalStateException: getOutputStream() has already been called for this response
	at org.apache.catalina.connector.Response.getWriter(Response.java:619)
	at org.apache.catalina.connector.ResponseFacade.getWriter(ResponseFacade.java:211)
	at javax.servlet.ServletResponseWrapper.getWriter(ServletResponseWrapper.java:109)
	at com.bstek.ureport.console.UReportServlet.service(UReportServlet.java:84)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:96)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.zsplat.backend.foundation.service.license.LicenseFilter.doFilter(LicenseFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:123)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:105)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)`

*  #### 相关截图：
![image](https://user-images.githubusercontent.com/20122457/59907795-7e569f00-943e-11e9-8359-b00ee108a139.png)

![image](https://user-images.githubusercontent.com/20122457/59907869-a7772f80-943e-11e9-8f55-01c70f06ed57.png)

![image](https://user-images.githubusercontent.com/20122457/59907898-b8c03c00-943e-11e9-9019-56acd82723b8.png)

![image](https://user-images.githubusercontent.com/20122457/59907929-c8d81b80-943e-11e9-8d86-24a9bc6cf407.png)

![image](https://user-images.githubusercontent.com/20122457/59907988-f329d900-943e-11e9-8bb9-935bccb0ac70.png)

**Comment by zsplatzangy** [comment]
项目配置问题，mybatis没有映射

**Comment by tank437** [comment]
请问怎么解决的，我也遇到这个问题了

**Comment by tank437** [comment]
> 项目配置问题，mybatis没有映射

具体是哪里有问题呢，我也碰到这个问题了

**Comment by zsplatzangy** [comment]
> > 项目配置问题，mybatis没有映射
> 
> 具体是哪里有问题呢，我也碰到这个问题了

emmmm，时间有点久，我记得是放置mybatis映射文件的文件夹命名问题，比如我直接创建了一个文件夹叫mapper.xx，但是IDE实际只创建了一个文件夹，而不是生成两个文件夹mapper和xx，所以需要创建两次文件夹。
希望能够帮到你，好运~

**Comment by 203579397** [comment]
我也遇到了这个问题。就是在保存的时候弹出“保存报表文件”弹窗报这个错误，大概意思是这个response被用了两次

**Comment by g1104434276** [comment]
我配置完成以后对项目进行重新构建就解决了
