### ISSUE TITLE
日期格式化问题

### ISSUE THREAD

**Issue by zDream** [youseries/ureport#447]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：2.2.9

*  #### 遇到的问题描述：
无法对日期格式化

*  #### 涉及到的异常信息（完整异常信息）：
com.bstek.ureport.exception.ConvertException: Can not convert 2019-08-07 11:24:40.0 to BigDecimal. 
at com.bstek.ureport.Utils.toBigDecimal(Utils.java:212) 
at com.bstek.ureport.expression.function.SumFunction.execute(SumFunction.java:54) 
at com.bstek.ureport.expression.model.expr.FunctionExpression.compute(FunctionExpression.java:62) 
at com.bstek.ureport.expression.model.expr.JoinExpression.compute(JoinExpression.java:46) 
at com.bstek.ureport.expression.model.expr.BaseExpression.execute(BaseExpression.java:37) 
at com.bstek.ureport.expression.model.expr.ExpressionBlock.compute(ExpressionBlock.java:38) 
at com.bstek.ureport.expression.model.expr.BaseExpression.execute(BaseExpression.java:37) 
at com.bstek.ureport.build.compute.ExpressionValueCompute.compute(ExpressionValueCompute.java:60) 
at com.bstek.ureport.build.DataCompute.buildCellData(DataCompute.java:64) 
at com.bstek.ureport.build.Context.buildCellData(Context.java:146) 
at com.bstek.ureport.build.ReportBuilder.buildCell(ReportBuilder.java:100) 
at com.bstek.ureport.build.ReportBuilder.buildReport(ReportBuilder.java:81) 
at com.bstek.ureport.console.html.HtmlPreviewServletAction.loadReport(HtmlPreviewServletAction.java:279) 
at com.bstek.ureport.console.html.HtmlPreviewServletAction.execute(HtmlPreviewServletAction.java:78) 
at com.bstek.ureport.console.UReportServlet.service(UReportServlet.java:81) 
at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) 
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) 
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) 
at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) 
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) 
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) 
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) 
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) 
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490) 
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) 
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) 
at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678) 
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) 
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) 
at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408) 
at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) 
at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:853) 
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1587) 
at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) 
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) 
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) 
at java.lang.Thread.run(Thread.java:748) 
 

*  #### 相关截图：
![image](https://user-images.githubusercontent.com/16067566/63208360-89a80d00-c105-11e9-95fa-5a5f8b0bb6de.png)

**Comment by zDream** [comment]
如何 对该日期格式化  2019-08-07 11:24:40.0
