### ISSUE TITLE
使用条件属性在隐藏列时报空指针异常

### ISSUE THREAD

**Issue by beijibingdong** [youseries/ureport#490]
*  #### 当前使用的UReport的具体版本号：2.2.9
*  #### 遇到的问题描述：使用条件属性在隐藏列时报空指针异常
*  #### 涉及到的异常信息（完整异常信息）：
报表计算出错，错误信息如下：
java.lang.NullPointerException
at com.bstek.ureport.build.HideRowColumnBuilder.doHideProcessColumn(HideRowColumnBuilder.java:65)
at com.bstek.ureport.build.Context.doHideProcessColumn(Context.java:111)
at com.bstek.ureport.model.Cell.doComputeConditionProperty(Cell.java:341)
at com.bstek.ureport.model.Cell.doCompute(Cell.java:257)
at com.bstek.ureport.build.ReportBuilder.recomputeCells(ReportBuilder.java:310)
at com.bstek.ureport.build.ReportBuilder.buildReport(ReportBuilder.java:85)
at com.bstek.ureport.export.ReportRender.render(ReportRender.java:57)
at com.bstek.ureport.export.ExportManagerImpl.exportHtml(ExportManagerImpl.java:47)
at com.bstek.ureport.console.html.HtmlPreviewServletAction.loadReport(HtmlPreviewServletAction.java:317)
at com.bstek.ureport.console.html.HtmlPreviewServletAction.execute(HtmlPreviewServletAction.java:78)
at com.bstek.ureport.console.UReportServlet.service(UReportServlet.java:81)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85)
at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
at com.common.VerificationFilter.doFilter(VerificationFilter.java:38)
at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:60)
at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:284)
at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:263)
at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:174)
at io.undertow.server.Connectors.executeRootHandler(Connectors.java:202)
at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:793)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
 
*  #### 相关截图：
![image](https://user-images.githubusercontent.com/19652478/71395598-914a6600-2651-11ea-8beb-0a04fba92ec4.png)
![image](https://user-images.githubusercontent.com/19652478/71395628-ab844400-2651-11ea-9038-af5539aa6179.png)

**Comment by 1125068334** [comment]
你好，请问这个问题后来怎么解决的呢？
