### ISSUE TITLE
Spring boot实现数据库自定义存储器：getOutputStream() has already been called for this response

### ISSUE THREAD

**Issue by Tom-Yu** [youseries/ureport#540]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：
2.2.9

*  #### 遇到的问题描述：
项目环境：
JDK1.8
SpringBoot 2.2.5。RELEASE
Mybatis-plus 3.3.2

涉及到的异常信息（完整异常信息）：
java.lang.IllegalStateException: getOutputStream() has already been called for this response at org.apache.catalina.connector.Response.getWriter(Response.java:619) at org.apache.catalina.connector.ResponseFacade.getWriter(ResponseFacade.java:211) at javax.servlet.ServletResponseWrapper.getWriter(ServletResponseWrapper.java:109) at com.bstek.ureport.console.UReportServlet.service(UReportServlet.java:84) at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilt

**Comment by bobli0904** [comment]
我也遇到了，请问解决了吗
