### ISSUE TITLE
poi兼容性问题

### ISSUE THREAD

**Issue by imyuyu** [youseries/ureport#573]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### JDK版本：
11

*  #### POI版本：
5.2.2

*  #### 当前使用的UReport的具体版本号：
2.2.9

*  #### 遇到的问题描述：
当与poi升级到5.2.2时，只能导出pdf,其余的word、excel均无法导出。

*  #### 涉及到的异常信息（完整异常信息）：
Word
```
java.lang.NoSuchMethodError: 'void org.openxmlformats.schemas.wordprocessingml.x2006.main.CTPageSz.setW(java.math.BigInteger)'
		at com.bstek.ureport.export.word.high.WordProducer.produce(WordProducer.java:98)
```

Excel
```
java.lang.NoSuchMethodError: 'void org.apache.poi.xssf.usermodel.XSSFColor.<init>(java.awt.Color)'
		at com.bstek.ureport.export.excel.high.CellStyleContext.buildXSSFColor(CellStyleContext.java:260)
		at com.bstek.ureport.export.excel.high.CellStyleContext.createNewCellStyle(CellStyleContext.java:92)
		at com.bstek.ureport.export.excel.high.CellStyleContext.produceXSSFCellStyle(CellStyleContext.java:49)
		at com.bstek.ureport.export.excel.high.builder.ExcelBuilderDirect.build(ExcelBuilderDirect.java:111)
		at com.bstek.ureport.export.excel.high.ExcelProducer.doProduce(ExcelProducer.java:45)
		at com.bstek.ureport.export.excel.high.ExcelProducer.produce(ExcelProducer.java:35)
```
分页Excel
```
java.lang.IllegalStateException: 当前响应已经调用了方法getOutputStream()
		at org.apache.catalina.connector.Response.getWriter(Response.java:584)
		at org.apache.catalina.connector.ResponseFacade.getWriter(ResponseFacade.java:227)
		at javax.servlet.ServletResponseWrapper.getWriter(ServletResponseWrapper.java:114)
		at org.springframework.session.web.http.OnCommittedResponseWrapper.getWriter(OnCommittedResponseWrapper.java:152)
		at javax.servlet.ServletResponseWrapper.getWriter(ServletResponseWrapper.java:114)
		at javax.servlet.ServletResponseWrapper.getWriter(ServletResponseWrapper.java:114)
		at org.springframework.security.web.util.OnCommittedResponseWrapper.getWriter(OnCommittedResponseWrapper.java:156)
		at javax.servlet.ServletResponseWrapper.getWriter(ServletResponseWrapper.java:114)
		at org.springframework.security.web.util.OnCommittedResponseWrapper.getWriter(OnCommittedResponseWrapper.java:156)
		at com.bstek.ureport.console.UReportServlet.service(UReportServlet.java:84)
```

*  #### 相关截图：

**Comment by imyuyu** [comment]
已经拉代码自行处理，参考 [poi5.x适配](https://github.com/youseries/ureport/compare/master...imyuyu:2.2.9.jdk11#diff-9688ac0ab74480fe8cfc52674815837468d6d346e3d35a11dfa80ac7087cde3d)

**Comment by wsxe9988** [comment]
@imyuyu 我poi 升级5.x后 带图表的报表导出excel后，图表对应的图片不显示，是空白，你有遇到这个现象么

**Comment by imyuyu** [comment]
> 

没有遇到过，我们没怎么用图表，主要是复杂的中国式报表，可以自己拉代码看看。

**Comment by imyuyu** [comment]
> @imyuyu 我poi 升级5.x后 带图表的报表导出excel后，图表对应的图片不显示，是空白，你有遇到这个现象么

没有遇到过，我们没怎么用图表，主要是复杂的中国式报表，可以自己拉代码看看。

**Comment by wsxe9988** [comment]
我试了 把SXSSFWorkbook  改成 XSSFWorkbook 后就可以了

**Comment by 858882847** [comment]
> 我试了 把SXSSFWorkbook 改成 XSSFWorkbook 后就可以了
excel中存在图片导入到UReport里，只有文字信息进去了还要边框样式，只有图片没进去是什么原因
